#!/usr/bin/env bash

docker image build                         \
    --build-arg USERNAME="${USER}"         \
    --build-arg USERID="$(id -u ${USER})"  \
    --build-arg LOCALBUILD="true"          \
    --file builder/Dockerfile              \
    --tag svr_info_builder:v4              \
    .
